# NUMPY 基本運算


<font  size=4 >維度相同的矩陣相加減:</font><br>
##不同則無法相加或相減

In [18]:
import numpy as np
a = np.arange( 4,8 ).reshape(2,2)
b = np.arange( 4 ).reshape(2,2)
c = a + b
d = a - b
print('a:\n',a)
print('b:\n',b)
print('c:\n',c)
print('d:\n',d)

a:
 [[4 5]
 [6 7]]
b:
 [[0 1]
 [2 3]]
c:
 [[ 4  6]
 [ 8 10]]
d:
 [[4 4]
 [4 4]]


<font  size=4 >維度相同的矩陣加減常數:</font><br>

In [19]:
c = a + 5
d = a - 5
print('c:\n',c)
print('d:\n',d)


c:
 [[ 9 10]
 [11 12]]
d:
 [[-1  0]
 [ 1  2]]


<font  size=4 >矩陣的相乘:</font><br>

In [21]:
c = a * b     #相同位置的乘法
d = a.dot(b)  #真實的矩陣乘法 也可寫作: a @ b
print('c:\n',c)  

print('d:\n',d) 

c:
 [[ 0  5]
 [12 21]]
d:
 [[10 19]
 [14 27]]


<font  size=4 >矩陣的轉置:</font><br>

In [23]:
c = a.T
print('a:\n',a)
print('c:\n',c)

a:
 [[4 5]
 [6 7]]
c:
 [[4 6]
 [5 7]]
