In [1]:
import pandas as pd #載入pandas
import numpy as np #載入numpy

### 將兩個字典組成DataFrame格式   *D和F需大寫

In [2]:
dict1={'May':18,'Scott':25,'Mary':21,'John':20}
dict2={'May':178,'Scott':167,'Mary':177,'John':180}
pandas1=pd.DataFrame({'age':dict1,'height':dict2})
print(pandas1)

       age  height
John    20     180
Mary    21     177
May     18     178
Scott   25     167


In [7]:
print('列索引: ',pandas1.index)
print('欄索引: ',pandas1.columns)
print('值: \n',pandas1.values)

列索引:  Index(['John', 'Mary', 'May', 'Scott'], dtype='object')
欄索引:  Index(['age', 'height'], dtype='object')
值: 
 [[ 20 180]
 [ 21 177]
 [ 18 178]
 [ 25 167]]


### DataFrame取值的方式:

In [11]:
print(pandas1['age'])  #取整欄
print()
print(pandas1['age']['Mary']) #取值

John     20
Mary     21
May      18
Scott    25
Name: age, dtype: int64

21


### Numpy二維取值的方式:

In [24]:
numpy1=np.random.randint(0,9,(4,3))
print(numpy1)
print()
print(numpy1[0])  #取列
print()
print(numpy1[0][2]) #取值

[[1 3 8]
 [1 7 8]
 [3 2 0]
 [7 3 3]]

[1 3 8]

8


### 利用Numpy製作DataFrame

In [27]:
pandas2=pd.DataFrame(np.random.randint(0,9,(5,3)),columns=['a','b','c'],index=['A','B','C','D','E'])
print(pandas2)

   a  b  c
A  7  6  7
B  0  7  5
C  6  4  6
D  6  1  3
E  5  8  1


### DataFrame的.index 也是陣列
但index不允許直接賦值

In [28]:
pandas_index=pandas2.index[1:3]
print(pandas_index)

Index(['B', 'C'], dtype='object')


### DataFrame的Index 也有集合的特性 ※這裡的i為大寫

In [31]:
pdi1=pd.Index([1,3,5,7,9,11,13])
pdi2=pd.Index([1,2,5,4,9,6,13])
print(pdi1 & pdi2) #有重疊的值
print(pdi1 | pdi2) #所有值
print(pdi1 ^ pdi2) #不重疊的值

Int64Index([1, 5, 9, 13], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 6, 7, 9, 11, 13], dtype='int64')
Int64Index([2, 3, 4, 6, 7, 11], dtype='int64')
